//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaeTerra.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviso
    {
        public int codAviso { get; set; }
        public string titulo { get; set; }
        public string mensagem { get; set; }
        public Nullable<bool> ativo { get; set; }
    }
}
