//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaeTerra.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedorDocumento
    {
        public int codFornecedorDocumento { get; set; }
        public int codFornecedor { get; set; }
        public string nome { get; set; }
        public byte[] arquivo { get; set; }
        public Nullable<bool> aprovado { get; set; }
        public Nullable<System.DateTime> dataAprovado { get; set; }
        public Nullable<int> codUsuarioAprovado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
