//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaeTerra.Infraestrutura.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnileverDBEntities : DbContext
    {
        public UnileverDBEntities()
            : base("name=UnileverDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aviso> tbAvisos { get; set; }
        public virtual DbSet<Fornecedor> tbFornecedores { get; set; }
        public virtual DbSet<FornecedorDocumento> tbFornecedoresDocumentos { get; set; }
        public virtual DbSet<MateriaPrima> tbMateriasPrimas { get; set; }
        public virtual DbSet<Pedido> tbPedidos { get; set; }
        public virtual DbSet<PedidoItem> tbPedidosItens { get; set; }
        public virtual DbSet<PedidoMateriaPrima> tbPedidosMateriasPrimas { get; set; }
        public virtual DbSet<Usuario> tbUsuarios { get; set; }
    }
}
