//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaeTerra.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPrima
    {
        public int codMateriaPrima { get; set; }
        public string nome { get; set; }
        public string grupo { get; set; }
        public string classificacao { get; set; }
        public Nullable<decimal> ultimoPreco { get; set; }
    }
}
