//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaeTerra.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItem
    {
        public int codPedidoItem { get; set; }
        public int codPedido { get; set; }
        public int codFornecedor { get; set; }
        public int codMateriaPrima { get; set; }
        public Nullable<decimal> quantidade { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> dataEntrega { get; set; }
        public Nullable<bool> aprovado { get; set; }
    }
}
